import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author SumanMichael
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
          
        initComponents();
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        tfusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        tfcnfpswd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        tfcontact = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        tflocation = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("images\\home_bg.jpg")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        getContentPane().add(jLabel1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, 18));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, 10));

        jButton1.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Register");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 210, 40));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tfusername.setBackground(new java.awt.Color(51, 51, 255));
        tfusername.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tfusername.setForeground(new java.awt.Color(255, 255, 255));
        tfusername.setBorder(null);
        jPanel1.add(tfusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 200, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 18));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 210, 10));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Confirm Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 18));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 210, 10));

        tfcnfpswd.setBackground(new java.awt.Color(51, 51, 255));
        tfcnfpswd.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tfcnfpswd.setForeground(new java.awt.Color(255, 255, 255));
        tfcnfpswd.setBorder(null);
        jPanel1.add(tfcnfpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 200, 30));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 18));

        tfemail.setBackground(new java.awt.Color(51, 51, 255));
        tfemail.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tfemail.setForeground(new java.awt.Color(255, 255, 255));
        tfemail.setBorder(null);
        jPanel1.add(tfemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 18));

        tfname.setBackground(new java.awt.Color(51, 51, 255));
        tfname.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tfname.setForeground(new java.awt.Color(255, 255, 255));
        tfname.setBorder(null);
        jPanel1.add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 200, 30));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 210, 10));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Location");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 18));

        tfcontact.setBackground(new java.awt.Color(51, 51, 255));
        tfcontact.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tfcontact.setForeground(new java.awt.Color(255, 255, 255));
        tfcontact.setBorder(null);
        jPanel1.add(tfcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 200, 30));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 210, 10));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 210, 10));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, 18));

        tflocation.setBackground(new java.awt.Color(51, 51, 255));
        tflocation.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        tflocation.setForeground(new java.awt.Color(255, 255, 255));
        tflocation.setBorder(null);
        jPanel1.add(tflocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 200, 30));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 255));
        jPasswordField1.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 200, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 198;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.3;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-ENimagesinitComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       

		            int x = 0;  
		            String s1 = tfname.getText();  
		            String s2 = tfusername.getText(); 
		            String s5 = tfemail.getText(); 
		            char[] s3 = jPasswordField1.getPassword();  
		            String s9 = tfcnfpswd.getText();   
		            String s8 = new String(s3);   
		             
		            String s6 = tflocation.getText();  
		            String s7 = tfcontact.getText();  
		            if (s8.equals(s9))  
		            {  
		                try  
		                {  
		                   Class.forName("oracle.jdbc.driver.OracleDriver");  
		      
		    //step2 create  the connection object  
		                    Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","rgukt123");  
		                     System.out.println(".........................");
		                    PreparedStatement ps = con.prepareStatement("insert into reg values(?,?,?,?,?,?)");  
		                    ps.setString(1, s1);  
		                    ps.setString(2, s2);  
		                    ps.setString(3, s5);  
		                  //  ps.setString(4, s9);  
		                    ps.setString(4, s8);  
		                    ps.setString(5, s6);  
		                    ps.setString(6, s7);  
		                    ResultSet rs = ps.executeQuery();  
		                    x++;  
		                    if (x > 0)   
		                    {  
		                       	JOptionPane.showMessageDialog(jButton1, "Data Saved Successfully");
		                      	new Login();
		                        this.dispose();  
		                    }  
		                    else
		                    {
		                    	  JOptionPane.showMessageDialog(jButton1, "Invalid Credentials"); 
		                    }
		                }  
		                catch (Exception ex)   
		                {  
		                    System.out.println("error occured"+ ex);
		                     JOptionPane.showMessageDialog(jButton1, "Invalid Credentials"); 

		                }  
		            }  
		            else  
		            {  
		                JOptionPane.showMessageDialog(jButton1, "Password Does Not Match");  
		            }   
		          }   



    //GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //  try {
        //     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        //         if ("Windows".equals(info.getName())) {
        //             javax.swing.UIManager.setLookAndFeel(info.getClassName());
        //             break;
        //         }
        //     }
        // } catch (ClassNotFoundException ex) {
        //     java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (InstantiationException ex) {
        //     java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (IllegalAccessException ex) {
        //     java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //     java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        // }
        // //</editor-fold>

        // /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //         f = new Register();
        //         f.setVisible(true);
        //     }
        // });
     
    }
    private static Register f; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField tfusername;
    private javax.swing.JTextField tfcontact;
    private javax.swing.JTextField tflocation;
    private javax.swing.JTextField tfcnfpswd;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfname;
    // End of variables declaration//GEN-ENimagesvariables
}
