/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;

/**
 *
 * @author SumanMichael
 */
public class Timing extends javax.swing.JFrame implements ActionListener{

	private String username;
	private String screen_no;
	private String movie_name;
	private String Date;
	private String slot;
	int a1,a2,a3,a4,b1,b2,b3,b4,c1,c2,c3,c4,d1,d2,d3,d4;
    /**
     * Creates new form Timing
     */
    public Timing(String username,String screen_no,String movie_name) {
    	this.username=username;
    	this.screen_no=screen_no;
    	this.movie_name=movie_name;
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
                }catch(Exception e){
                    e.printStackTrace();
                }
                initComponents();
                
            }
        });
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	PreparedStatement  ps1,ps2,ps3,ps4;
    	ResultSet  rs;
		try {
		Class.forName("oracle.jdbc.driver.OracleDriver");  
		  Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","rgukt123");  
		  ps1 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='23-04-2019' and tslot='10:30 AM'");
	  		Statement s = con.createStatement();
		  rs = s.executeQuery("select sum(fare) from "+screen_no+" where day='23-04-2019' and tslot='10:30 AM'");
		  rs.next();
		 a1=(int) (114-(rs.getFloat(1)/150));
		  ps2 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='23-04-2019' and tslot='1:30 PM'");
		 

		  rs = ps2.executeQuery();
		  rs.next();
		 a2=(int) (114-(rs.getFloat(1)/150));
		 
		  ps3 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='23-04-2019' and tslot='4:30 PM'");
		  
		 rs = ps3.executeQuery();
		  rs.next();
		 a3=(int) (114-(rs.getFloat(1)/150));
		 
		  ps4 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='23-04-2019' and tslot='7:30 PM'");
		  
		 rs = ps4.executeQuery();
		  rs.next();
		 a4=(int) (114-(rs.getFloat(1)/150));
		 
		 
		   ps1 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='24-04-2019' and tslot='10:30 AM'");
	  
		  rs = ps1.executeQuery();
		  rs.next();
		 b1=(int) (114-(rs.getFloat(1)/150));
		  ps2 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='24-04-2019' and tslot='1:30 PM'");
		  
		  rs = ps2.executeQuery();
		  rs.next();
		 b2=(int) (114-(rs.getFloat(1)/150));
		 
		  ps3 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='24-04-2019' and tslot='4:30 PM'");
		  
		 rs = ps3.executeQuery();
		  rs.next();
		 b3=(int) (114-(rs.getFloat(1)/150));
		 
		  ps4 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='24-04-2019' and tslot='7:30 PM'");
		  
		 rs = ps4.executeQuery();
		  rs.next();
		 b4=(int) (114-(rs.getFloat(1)/150));
		 
		   ps1 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='25-04-2019' and tslot=\'10:30 AM\'");
	  
		  rs = ps1.executeQuery();
		  rs.next();
		 c1=(int) (114-(rs.getFloat(1)/150));
		  ps2 = con.prepareStatement("select sum(fare) from "+screen_no+" where day=\'25-04-2019\' and tslot='1:30 PM'");
		  
		  rs = ps2.executeQuery();
		  rs.next();
		 c2=(int) (114-(rs.getFloat(1)/150));
		 
		  ps3 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='25-04-2019' and tslot='4:30 PM'");
		  
		 rs = ps3.executeQuery();
		  rs.next();
		 c3=(int) (114-(rs.getFloat(1)/150));
		 
		  ps4 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='25-04-2019' and tslot='7:30 PM'");
		  
		 rs = ps4.executeQuery();
		  rs.next();
		 c4=(int) (114-(rs.getFloat(1)/150));
		 
		 ps1 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='26-04-2019' and tslot='10:30 AM'");
	  
		  rs = ps1.executeQuery();
		  rs.next();
		 d1=(int) (114-(rs.getFloat(1)/150));
		 ps2 = con.prepareStatement("select sum(fare) from "+screen_no+" where day='26-04-2019' and tslot='1:30 PM'");
		  
		  rs = ps2.executeQuery();
		  rs.next();
		 d2=(int) (114-(rs.getFloat(1)/150));
		 
//		  
		 rs = ps3.executeQuery();
		  rs.next();
		 d3=(int) (114-(rs.getFloat(1)/150));
		 
		  ps4 = con.prepareStatement("select sum(fare) from "+screen_no+" where day=\'26-04-2019\' and tslot=\'7:30 PM\'");
		  
		 rs = ps4.executeQuery("select sum(fare) from "+screen_no+" where day=\'26-04-2019\' and tslot=\'7:30 PM\'");
		  rs.next();
		 d4=(int) (114-(rs.getFloat(1)/150));


		  
		}catch(Exception e) {System.out.println(e);}

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        d1b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        d1b2 = new javax.swing.JButton();
        d1b3 = new javax.swing.JButton();
        d1b4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        d2b1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jProgressBar7 = new javax.swing.JProgressBar();
        jProgressBar8 = new javax.swing.JProgressBar();
        d2b2 = new javax.swing.JButton();
        d2b3 = new javax.swing.JButton();
        d2b4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        d3b1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jProgressBar9 = new javax.swing.JProgressBar();
        jProgressBar10 = new javax.swing.JProgressBar();
        jProgressBar11 = new javax.swing.JProgressBar();
        jProgressBar12 = new javax.swing.JProgressBar();
        d3b2 = new javax.swing.JButton();
        d3b3 = new javax.swing.JButton();
        d3b4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        d4b1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jProgressBar13 = new javax.swing.JProgressBar();
        jProgressBar14 = new javax.swing.JProgressBar();
        jProgressBar15 = new javax.swing.JProgressBar();
        jProgressBar16 = new javax.swing.JProgressBar();
        d4b2 = new javax.swing.JButton();
        d4b3 = new javax.swing.JButton();
        d4b4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        d1b1.setBackground(new java.awt.Color(51, 51, 255));
        d1b1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d1b1.setForeground(new java.awt.Color(255, 255, 255));
        d1b1.setText("10:30 AM");
        d1b1.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel1.setText(movie_name+" 70mm AC");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel2.setText(screen_no);

        jProgressBar1.setValue(a1*100/114);

        jProgressBar2.setValue(a2*100/114);

        jProgressBar3.setValue(a3*100/114);

        jProgressBar4.setValue(a4*100/114);

        d1b2.setBackground(new java.awt.Color(51, 51, 255));
        d1b2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d1b2.setForeground(new java.awt.Color(255, 255, 255));
        d1b2.setText("1:30 PM");
        d1b2.setBorder(null);

        d1b3.setBackground(new java.awt.Color(51, 51, 255));
        d1b3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d1b3.setForeground(new java.awt.Color(255, 255, 255));
        d1b3.setText("4:30 PM");
        d1b3.setBorder(null);

        d1b4.setBackground(new java.awt.Color(51, 51, 255));
        d1b4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d1b4.setForeground(new java.awt.Color(255, 255, 255));
        d1b4.setText("7:30 PM");
        d1b4.setBorder(null);

        jLabel3.setText("Available :"+a1);

        jLabel4.setText("Available :"+a2);

        jLabel5.setText("Available :"+a3);

        jLabel6.setText("Available :"+a4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d1b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(d1b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(d1b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(279, 279, 279))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d1b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("23-04-2019", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        d2b1.setBackground(new java.awt.Color(51, 51, 255));
        d2b1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d2b1.setForeground(new java.awt.Color(255, 255, 255));
        d2b1.setText("10:30 AM");
        d2b1.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel7.setText(movie_name+" 70mm AC");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel8.setText(screen_no);

        jProgressBar5.setValue(b1*100/114);

        jProgressBar6.setValue(b2*100/114);

        jProgressBar7.setValue(b3*100/114);

        jProgressBar8.setValue(b4*100/114);

        d2b2.setBackground(new java.awt.Color(51, 51, 255));
        d2b2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d2b2.setForeground(new java.awt.Color(255, 255, 255));
        d2b2.setText("1:30 PM");
        d2b2.setBorder(null);

        d2b3.setBackground(new java.awt.Color(51, 51, 255));
        d2b3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d2b3.setForeground(new java.awt.Color(255, 255, 255));
        d2b3.setText("4:30 PM");
        d2b3.setBorder(null);

        d2b4.setBackground(new java.awt.Color(51, 51, 255));
        d2b4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d2b4.setForeground(new java.awt.Color(255, 255, 255));
        d2b4.setText("7:30 PM");
        d2b4.setBorder(null);

        jLabel9.setText("Available :"+b1);

        jLabel10.setText("Available :"+b2);

        jLabel11.setText("Available :"+b3);

        jLabel12.setText("Available :"+b4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d2b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(d2b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(d2b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11))
                            .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(279, 279, 279))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d2b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d2b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("24-04-2019", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        d3b1.setBackground(new java.awt.Color(51, 51, 255));
        d3b1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d3b1.setForeground(new java.awt.Color(255, 255, 255));
        d3b1.setText("10:30 AM");
        d3b1.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel13.setText(movie_name+" 70mm AC");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel14.setText(screen_no);

        jProgressBar9.setValue(c1*100/114);

        jProgressBar10.setValue(c2*100/114);

        jProgressBar11.setValue(c3*100/114);

        jProgressBar12.setValue(c4*100/114);

        d3b2.setBackground(new java.awt.Color(51, 51, 255));
        d3b2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d3b2.setForeground(new java.awt.Color(255, 255, 255));
        d3b2.setText("1:30 PM");
        d3b2.setBorder(null);

        d3b3.setBackground(new java.awt.Color(51, 51, 255));
        d3b3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d3b3.setForeground(new java.awt.Color(255, 255, 255));
        d3b3.setText("4:30 PM");
        d3b3.setBorder(null);

        d3b4.setBackground(new java.awt.Color(51, 51, 255));
        d3b4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d3b4.setForeground(new java.awt.Color(255, 255, 255));
        d3b4.setText("7:30 PM");
        d3b4.setBorder(null);

        jLabel15.setText("Available :"+c1);

        jLabel16.setText("Available :"+c2);

        jLabel17.setText("Available :"+c3);

        jLabel18.setText("Available :"+c4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d3b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16)))
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(d3b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(d3b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17))
                            .addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(279, 279, 279))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d3b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("25-04-2019", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        d4b1.setBackground(new java.awt.Color(51, 51, 255));
        d4b1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d4b1.setForeground(new java.awt.Color(255, 255, 255));
        d4b1.setText("10:30 AM");
        d4b1.setBorder(null);

        jLabel19.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel19.setText(movie_name+" 70mm AC");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        jLabel20.setText(screen_no);

        jProgressBar13.setValue(d1*100/114);

        jProgressBar14.setValue(d2*100/114);

        jProgressBar15.setValue(d3*100/114);

        jProgressBar16.setValue(d4*100/114);

        d4b2.setBackground(new java.awt.Color(51, 51, 255));
        d4b2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d4b2.setForeground(new java.awt.Color(255, 255, 255));
        d4b2.setText("1:30 PM");
        d4b2.setBorder(null);

        d4b3.setBackground(new java.awt.Color(51, 51, 255));
        d4b3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d4b3.setForeground(new java.awt.Color(255, 255, 255));
        d4b3.setText("4:30 PM");
        d4b3.setBorder(null);

        d4b4.setBackground(new java.awt.Color(51, 51, 255));
        d4b4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        d4b4.setForeground(new java.awt.Color(255, 255, 255));
        d4b4.setText("7:30 PM");
        d4b4.setBorder(null);

        jLabel21.setText("Available :"+d1);

        jLabel22.setText("Available :"+d2);

        jLabel23.setText("Available :"+d3);

        jLabel24.setText("Available :"+d4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jProgressBar14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(d4b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22)))
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(d4b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(d4b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel24)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel23))
                            .addComponent(jProgressBar16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(329, 329, 329))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(279, 279, 279))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d4b1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4b3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4b4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("26-04-2019", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

		d2b2.addActionListener(this);
		d2b3.addActionListener(this);
		d2b4.addActionListener(this);
		d3b2.addActionListener(this);
		d3b3.addActionListener(this);
		d3b4.addActionListener(this);
		d4b2.addActionListener(this);
		d4b3.addActionListener(this);
		d4b4.addActionListener(this);
		d1b1.addActionListener(this);
		d2b1.addActionListener(this);
		d3b1.addActionListener(this);
		d4b1.addActionListener(this);
		d1b2.addActionListener(this);
		d1b3.addActionListener(this);
		d1b4.addActionListener(this);

        pack();
        setLocationRelativeTo(null);
        setVisible(true);


    }// </editor-fold>//GEN-ENimagesinitComponents
    public void actionPerformed(ActionEvent ae){
    	this.dispose();
    	if(ae.getSource()==d1b1){
    		new Seats(username,screen_no,movie_name,d1b1.getText(),"23-04-2019");
    	}
    	else if(ae.getSource()==d1b2){
    		new Seats(username,screen_no,movie_name,d1b2.getText(),"23-04-2019");	
    	}
    	else if(ae.getSource()==d1b3){
    		new Seats(username,screen_no,movie_name,d1b3.getText(),"23-04-2019");
    	}else if(ae.getSource()==d1b4){
    		new Seats(username,screen_no,movie_name,d1b4.getText(),"23-04-2019");
    	}else if(ae.getSource()==d2b1){
    		new Seats(username,screen_no,movie_name,d2b1.getText(),"24-04-2019");
    	}else if(ae.getSource()==d2b2){
    		new Seats(username,screen_no,movie_name,d2b2.getText(),"24-04-2019");
    	}else if(ae.getSource()==d2b3){
    		new Seats(username,screen_no,movie_name,d2b3.getText(),"24-04-2019");
    	}else if(ae.getSource()==d2b4){
    		new Seats(username,screen_no,movie_name,d2b4.getText(),"24-04-2019");
    	}else if(ae.getSource()==d3b1){
    		new Seats(username,screen_no,movie_name,d3b1.getText(),"25-04-2019");
    	}else if(ae.getSource()==d3b2){
    		new Seats(username,screen_no,movie_name,d3b2.getText(),"25-04-2019");
    	}else if(ae.getSource()==d3b3){
    		new Seats(username,screen_no,movie_name,d3b3.getText(),"25-04-2019");
    	}else if(ae.getSource()==d3b4){
    		new Seats(username,screen_no,movie_name,d3b4.getText(),"25-04-2019");
    	}else if(ae.getSource()==d4b1){
    		new Seats(username,screen_no,movie_name,d4b1.getText(),"26-04-2019");
    	}else if(ae.getSource()==d4b2){
    		new Seats(username,screen_no,movie_name,d4b2.getText(),"26-04-2019");
    	}else if(ae.getSource()==d4b3){
    		new Seats(username,screen_no,movie_name,d4b3.getText(),"26-04-2019");
    	}else if(ae.getSource()==d4b4){
    		new Seats(username,screen_no,movie_name,d4b4.getText(),"26-04-2019");
    	}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(new Runnable() {
        //     public void run() {
        //        // Timing f = new Timing();

        //         f.setLocationRelativeTo(null);
        //         f.setVisible(true);
        //     }
        // });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton d2b2;
    private javax.swing.JButton d2b3;
    private javax.swing.JButton d2b4;
    private javax.swing.JButton d3b2;
    private javax.swing.JButton d3b3;
    private javax.swing.JButton d3b4;
    private javax.swing.JButton d4b2;
    private javax.swing.JButton d4b3;
    private javax.swing.JButton d4b4;
    private javax.swing.JButton d1b1;
    private javax.swing.JButton d2b1;
    private javax.swing.JButton d3b1;
    private javax.swing.JButton d4b1;
    private javax.swing.JButton d1b2;
    private javax.swing.JButton d1b3;
    private javax.swing.JButton d1b4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar11;
    private javax.swing.JProgressBar jProgressBar12;
    private javax.swing.JProgressBar jProgressBar13;
    private javax.swing.JProgressBar jProgressBar14;
    private javax.swing.JProgressBar jProgressBar15;
    private javax.swing.JProgressBar jProgressBar16;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-ENimagesvariables
}
